name: Docker

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2
    
      - name: Compute README.md
        run: |
          echo "# Biostatistics Docker Image" > README.md
          echo "" >> README.md
          echo "[![Docker](https://github.com/umr1283/docker_biostatistics/actions/workflows/docker.yml/badge.svg)](https://github.com/umr1283/docker_biostatistics/actions/workflows/docker.yml)" >> README.md
          echo "" >> README.md
          awk -F "=" 'NR >= 4 && NR <= 9 {sub(/^ENV /, "* ", $1); sub(/_VERSION/, ": `v", $1); print $1$2"`  "}' Dockerfile >> README.md
    
      - name: Commit README.md
        run: | 
          git config --local user.email "actions@github.com"
          git config --local user.name "UMR1283 Biostatistics"
          git commit README.md -m 'Update README.md' || echo "No changes to commit"
          git push || echo "No changes to commit"
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            umr1283/stat
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=dev
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: umr1283/stat
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
