on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  schedule:
    - cron: '0 0 01 */3 *'
  workflow_dispatch:

name: pull-docker

jobs:
  pull-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull Docker images
        run: |
          timeout 1s docker pull umr1283/stat:shiny-v0.14 || true
          timeout 1s docker pull umr1283/stat:R362 || true
          timeout 1s docker pull umr1283/stat:R363 || true
          timeout 1s docker pull umr1283/stat:R402 || true
          timeout 1s docker pull umr1283/stat:R403 || true
          timeout 1s docker pull umr1283/stat:3.6.3 || true
          timeout 1s docker pull umr1283/stat:4.0.4 || true
          timeout 1s docker pull umr1283/stat:4.0.5 || true
          timeout 1s docker pull umr1283/stat:4.1.0 || true
