on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  schedule:
    - cron: '0 0 01 */3 *'

name: pull-docker

jobs:
  pull-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull Docker images
        run: |
          timeout 1s docker pull umr1283/stat:shiny-v0.14 2> /dev/null
          timeout 1s docker pull umr1283/stat:R362 2> /dev/null
          timeout 1s docker pull umr1283/stat:R363 2> /dev/null
          timeout 1s docker pull umr1283/stat:R402 2> /dev/null
          timeout 1s docker pull umr1283/stat:R403 2> /dev/null
          timeout 1s docker pull umr1283/stat:3.6.3 2> /dev/null
          timeout 1s docker pull umr1283/stat:4.0.4 2> /dev/null
          timeout 1s docker pull umr1283/stat:4.0.5 2> /dev/null
