name: Update README.md

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compute README.md
      run: |
        echo "# Biostatistics Docker Image" > README.md
        echo "" >> README.md
        awk -F "=" 'NR >= 4 && NR <= 11 {sub(/^ENV /, "* ", $1); sub(/_VERSION/, ": `v", $1); print $1$2"`  "}' Dockerfile >> README.md
    - name: Commit README.md
      run: | 
        git config --global user.name "${{secrets.NAME}}"
        git commit README.md -m 'Update README.md' || echo "No changes to commit"
        git push || echo "No changes to commit"
